version: "2"
linters:
  enable:
    - gofumpt
  disable:
    # Disabling deprecated linters
    - exportloopref
    # To fix later
    - dupl
    - forcetypeassert
    # Disabling by decision
    - depguard
    - exhaustruct
    - prealloc
    - tagliatelle
linters-settings:
  gofumpt:
    enabled: true

