linters:
  enable-all: true
  disable:
    # Disabling deprecated linters
    - execinquery
    - exportloopref
    # To fix later
    - dupl
    - forcetypeassert
    - gomnd
    # Disabling by decision
    - depguard
    - exhaustruct
    - gofumpt
    - prealloc
    - tagliatelle

version: "2"
