services:
  data:
    image: mysql:5.7
    container_name: database
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tuiter
      MYSQL_USER: api
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
